<div class="jumbotron">
    <h1>Jumbotron heading</h1>
    <p class="lead">Cras justo odio, dapibus ac facilisis in, egestas eget quam. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
    <p><a class="btn btn-lg btn-success" href="#" role="button">Sign up today</a></p>
</div>

<div class="row marketing">
    <div class="col-lg-10">
        <?php foreach($comments as $comment){ ?>
            <h4><?= $comment['name'];?></h4>
            <p><?= $comment['comment'];?></p>
        <?php } ?>
    </div>
</div>

<div class="col-lg-12">
    <div>
        <p class="lead">Leave feedback</p>
    </div>
    <form method="post">
        <div class="form-group">
            <input class="form-control" name="name"
                   placeholder="Your name"
                <?php
                    if($user) {
                        echo "value='{$user}'";
                    }
                ?>/>
        </div>
        <div class="form-group">
            <textarea class="form-control" name="comment" rows="3"></textarea>
        </div>

        <button class="btn btn-default">Send!</button>
    </form>
</div>